package com.example.carimahasiswa

data class ItemsViewModelSearch(val cama: Int) {
    val getCama = when (cama) {
        1 -> "SAKA NUSI WIANDRA(5210411074), PT : UNIVERSITAS TEKNOLOGI YOGYAKARTA, Prodi: INFORMATIKA"
        2 -> "IVAN BHAGASKARA KARTASASMITA(5210411100), PT : UNIVERSITAS TEKNOLOGI YOGYAKARTA, Prodi: INFORMATIKA"
        3 -> "ADITYA WARMAN(5210411097), PT : UNIVERSITAS TEKNOLOGI YOGYAKARTA, Prodi: INFORMATIKA"
        4 -> "AHMAD FAIZIN(5210411073), PT : UNIVERSITAS TEKNOLOGI YOGYAKARTA, Prodi: INFORMATIKA"
        else -> "NULL"
    }
}